 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/views", type: :request do
  # View. As you add validations to View, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      View.create! valid_attributes
      get views_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      view = View.create! valid_attributes
      get view_url(view)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_view_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      view = View.create! valid_attributes
      get edit_view_url(view)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new View" do
        expect {
          post views_url, params: { view: valid_attributes }
        }.to change(View, :count).by(1)
      end

      it "redirects to the created view" do
        post views_url, params: { view: valid_attributes }
        expect(response).to redirect_to(view_url(View.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new View" do
        expect {
          post views_url, params: { view: invalid_attributes }
        }.to change(View, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post views_url, params: { view: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested view" do
        view = View.create! valid_attributes
        patch view_url(view), params: { view: new_attributes }
        view.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the view" do
        view = View.create! valid_attributes
        patch view_url(view), params: { view: new_attributes }
        view.reload
        expect(response).to redirect_to(view_url(view))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        view = View.create! valid_attributes
        patch view_url(view), params: { view: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested view" do
      view = View.create! valid_attributes
      expect {
        delete view_url(view)
      }.to change(View, :count).by(-1)
    end

    it "redirects to the views list" do
      view = View.create! valid_attributes
      delete view_url(view)
      expect(response).to redirect_to(views_url)
    end
  end
end
